name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.300

      - name: Pack
        run: dotnet pack burtonrodman.FieldInjectionGenerator/burtonrodman.FieldInjectionGenerator.csproj -c Release

      - name: Publish NuGet Package
        run: dotnet nuget push /home/runner/work/FieldInjectionGenerator/FieldInjectionGenerator/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate